# Generated by Django 3.2.4 on 2022-11-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='matric_no',
            new_name='userid',
        ),
    ]
