# Generated by Django 3.2.4 on 2022-11-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_matric_no_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
