# Generated by Django 3.2.4 on 2022-11-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20221101_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='er',
            new_name='user',
        ),
    ]
