# Generated by Django 3.2.4 on 2022-11-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_rename_er_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='student',
        ),
    ]
