# Generated by Django 3.2.4 on 2022-11-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_alter_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='priority',
        ),
    ]
