# Generated by Django 3.2.4 on 2022-11-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_remove_position_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
