# Generated by Django 4.1.3 on 2022-11-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_candidate_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
