# Generated by Django 4.1.3 on 2022-11-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0009_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='voter',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
