# Generated by Django 4.1.3 on 2022-11-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0010_votes_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='voter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
