# Generated by Django 4.1.3 on 2022-11-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0011_alter_votes_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin1.candidate'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin1.position'),
        ),
    ]
