# Generated by Django 4.1.3 on 2022-12-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0014_alter_votes_candidate_alter_votes_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='candidate',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='position',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='voter',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
